modLoader="javafml"
loaderVersion="[4,)"
license="LGPLv3"

[[mods]]
modId="mafish_crafting"
version="1.01"
displayName="Mafish Crafting"
displayURL="https://github.com/SystemFileB/mafish-extras/tree/mafish-crafting"
credits="E"
authors="SystemFileB"
description="\u8BA9\u9A6C\u592B\u9C7C\u6A21\u7EC4\u7684\u7269\u54C1\u4ECD\u7136\u53EF\u4EE5\u5728\u751F\u5B58\u4E2D\u83B7\u5F97"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.mafish_crafting]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.mafish_crafting]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"




# Start of user code block dependencies configuration
[[dependencies.mafish_crafting]]
modId="neomafishmod"
type="required"
versionRange="[0.0.5,)"
ordering="NONE"
side="BOTH"
# End of user code block dependencies configuration
